/var/log/kodi/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 kodi kodi
    sharedscripts
    postrotate
        systemctl kill --signal=USR1 kodi-backend.service 2>/dev/null || true
    endscript
}
